// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LiveVersusDacpacPlayground.Models;

public partial class LiveVersusDacpacPlaygroundContext : DbContext
{
    public LiveVersusDacpacPlaygroundContext(DbContextOptions<LiveVersusDacpacPlaygroundContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SomeTable> SomeTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.SomeTableConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
