// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace LiveVersusDacpacPlayground.Models;

public partial class SomeTable
{
    public int SomeTableId { get; set; }

    public long SomeBigInt { get; set; } = 0;
}
