// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Issue3342.Models;

public partial class Issue3342Context : DbContext
{
    public Issue3342Context(DbContextOptions<Issue3342Context> options)
        : base(options)
    {
    }

    public virtual DbSet<TableOne> TableOnes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TableOne>(entity =>
        {
            entity.HasKey(e => e.TableOneId).HasName("PK_dbo_TableOne");

            entity.ToTable("TableOne");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}