// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Issue3342.Models;

public partial class TableOne
{
    public int TableOneId { get; set; }
}