// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DockerPlayground.Models
{
    public partial class StoGetSomeDataDirectTypeMatrixResult
    {
        public int? IntValue { get; set; }
        public long? BigIntValue { get; set; }
        [Column("DecimalValue", TypeName = "decimal(10,2)")]
        public decimal? DecimalValue { get; set; }
        [Column("NumericValue", TypeName = "decimal(12,4)")]
        public decimal? NumericValue { get; set; }
        [StringLength(100)]
        public string? StringValue { get; set; }
        [StringLength(50)]
        public string? AnsiStringValue { get; set; }
        [StringLength(2147483647)]
        public string? MaxStringValue { get; set; }
        [StringLength(128)]
        public string? SysNameValue { get; set; }
        public DateOnly? DateValue { get; set; }
        public DateTime? DateTime2Value { get; set; }
        public TimeOnly? TimeValue { get; set; }
        public Guid? GuidValue { get; set; }
        public bool? BitValue { get; set; }
        public byte[]? BinaryValue { get; set; }
        public byte[]? MaxBinaryValue { get; set; }
    }
}
