// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Issue3341.Models;

public partial class Bin
{
    public int BinId { get; set; }

    public int InventoryNodeId { get; set; }

    public byte InventoryNodeTypeCode { get; set; }

    public virtual InventoryNode InventoryNode { get; set; } = null!;

    public virtual InventoryNodeTypeLookup InventoryNodeTypeCodeNavigation { get; set; } = null!;
}