// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Issue3341.Models;

public partial class InventoryNode
{
    public int InventoryNodeId { get; set; }

    public byte InventoryNodeTypeCode { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();

    public virtual InventoryNodeTypeLookup InventoryNodeTypeCodeNavigation { get; set; } = null!;
}