// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Issue3341.Models;

public partial class InventoryNodeTypeLookup
{
    public byte InventoryNodeTypeCode { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();

    public virtual ICollection<InventoryNode> InventoryNodes { get; set; } = new List<InventoryNode>();
}