// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Issue3341.Models;

public partial class Issue3341Context : DbContext
{
    public Issue3341Context(DbContextOptions<Issue3341Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Bin> Bins { get; set; }

    public virtual DbSet<InventoryNode> InventoryNodes { get; set; }

    public virtual DbSet<InventoryNodeTypeLookup> InventoryNodeTypeLookups { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bin>(entity =>
        {
            entity.HasKey(e => e.BinId).HasName("PK_dbo_Bin");

            entity.ToTable("Bin");

            entity.Property(e => e.InventoryNodeTypeCode).HasComputedColumnSql("(CONVERT([tinyint],(8)))", true);

            entity.HasOne(d => d.InventoryNodeTypeCodeNavigation).WithMany(p => p.Bins)
                .HasForeignKey(d => d.InventoryNodeTypeCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo_Bin_dbo_InventoryNodeTypeCode");

            entity.HasOne(d => d.InventoryNode).WithMany(p => p.Bins)
                .HasPrincipalKey(p => new { p.InventoryNodeId, p.InventoryNodeTypeCode })
                .HasForeignKey(d => new { d.InventoryNodeId, d.InventoryNodeTypeCode })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo_Bin_InventoryNodeId_InventoryNodeTypeCode_dbo_InventoryNode");
        });

        modelBuilder.Entity<InventoryNode>(entity =>
        {
            entity.HasKey(e => e.InventoryNodeId).HasName("PK_dbo_InventoryNode");

            entity.ToTable("InventoryNode");

            entity.HasIndex(e => new { e.InventoryNodeId, e.InventoryNodeTypeCode }, "UQ_dbo_InventoryNode_InventoryNodeId_InventoryNodeTypeCode").IsUnique();

            entity.HasOne(d => d.InventoryNodeTypeCodeNavigation).WithMany(p => p.InventoryNodes)
                .HasForeignKey(d => d.InventoryNodeTypeCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo_InventoryNode_InventoryNodeTypeLookup");
        });

        modelBuilder.Entity<InventoryNodeTypeLookup>(entity =>
        {
            entity.HasKey(e => e.InventoryNodeTypeCode).HasName("PK_dbo_InventoryNodeTypeLookup");

            entity.ToTable("InventoryNodeTypeLookup");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}