// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DatabaseBuildTestHarness.Models;

public partial class DatabaseBuildTestHarnessContext : DbContext
{
    public DatabaseBuildTestHarnessContext(DbContextOptions<DatabaseBuildTestHarnessContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MessageFault> MessageFaults { get; set; }

    public virtual DbSet<SomeTable> SomeTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MessageFault>(entity =>
        {
            entity.Property(e => e.MessageFaultId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<SomeTable>(entity =>
        {
            entity.HasKey(e => e.SomeTableId).HasName("PK_dbo_SomeTable");

            entity.Property(e => e.ColumnWithDefault).HasComment("The location''s address");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}