// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DatabaseBuildTestHarness.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseBuildTestHarness.Models
{
    public partial interface IDatabaseBuildTestHarnessContextProcedures
    {
        Task<List<StoGetSomeDataResult>?> StoGetSomeDataAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
