// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseBuildTestHarness.Models;

[Keyless]
[Table("MessageFault")]
[Index("MessageFaultStatusCode", "FaultedTimestamp", Name = "IX_dbo_MessageFault_MessageFaultStatusCode_FaultedTimestamp")]
public partial class MessageFault
{
    public int MessageFaultId { get; set; }

    public DateTimeOffset FaultedTimestamp { get; set; }

    public byte MessageFaultStatusCode { get; set; }
}