// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseBuildTestHarness.Models;

[Table("SomeTable")]
public partial class SomeTable
{
    [Key]
    public int SomeTableId { get; set; }

    /// <summary>
    /// The location&apos;&apos;s address
    /// </summary>
    public long ColumnWithDefault { get; set; }
}