// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LiveVersusDacpacPlayground.Models.Configurations;

public partial class SomeTableConfiguration : IEntityTypeConfiguration<SomeTable>
{
    public void Configure(EntityTypeBuilder<SomeTable> entity)
    {
        entity.HasKey(e => e.SomeTableId).HasName("PK_readModel_SomeTable");

        entity.ToTable("SomeTable");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<SomeTable> modelBuilder);
}
